version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parkinglot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parkinglot-network

  app:

    build: .
    ports:
      - "8080:8080"
    networks:
      - parkinglot-network
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  parkinglot-network:
